// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb7Yl6doslty7C6A4ZF1yfCLktrOWS4OQ',
    appId: '1:473085981372:web:0ce9b6238c0615299656b9',
    messagingSenderId: '473085981372',
    projectId: 'fir-ce3ce',
    authDomain: 'fir-ce3ce.firebaseapp.com',
    storageBucket: 'fir-ce3ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbrjpIqroi9kfqNe4vEB-lvzdY8IqXrjk',
    appId: '1:473085981372:android:c742c5c9071fa0f19656b9',
    messagingSenderId: '473085981372',
    projectId: 'fir-ce3ce',
    storageBucket: 'fir-ce3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAar39e7L5MxOpbZJyS6AVVyK8ky5g2SrI',
    appId: '1:473085981372:ios:12272286e82864869656b9',
    messagingSenderId: '473085981372',
    projectId: 'fir-ce3ce',
    storageBucket: 'fir-ce3ce.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAar39e7L5MxOpbZJyS6AVVyK8ky5g2SrI',
    appId: '1:473085981372:ios:12272286e82864869656b9',
    messagingSenderId: '473085981372',
    projectId: 'fir-ce3ce',
    storageBucket: 'fir-ce3ce.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb7Yl6doslty7C6A4ZF1yfCLktrOWS4OQ',
    appId: '1:473085981372:web:e9692975d617c2d39656b9',
    messagingSenderId: '473085981372',
    projectId: 'fir-ce3ce',
    authDomain: 'fir-ce3ce.firebaseapp.com',
    storageBucket: 'fir-ce3ce.appspot.com',
  );
}
